# Webdevelopment

Ich habe im Verlauf meines Praktikums gelernt, dass es insbesondere auch sehr wichtig ist, dass ich einem breitem Publikum zeigen kann, was ich tue. 

Hierzu sind Kenntnisse in Webdevelopment sehr gut & ergänzend zu meinen Data Science Kenntnissen. 

**Deshalb liste ich hier alle Anforderungen im Bereich von Webdevelopment auf, die ich noch nicht kenne**.

## GraphQL

## Was ist das 

GraphQL is a **query language** for APIs.

> What is a Query Language?

This is a **programming language that requests and retrieves data from database- & information-systems by sending queries**, similarly to `SQL`.

## Quelle

- <u>**Webseite (Home)**</u>: https://graphql.org/
- <u>**Documentation**</u>: https://graphql.org/learn/


## Typescript

### Was ist das?

- `TypeScript` **adds additional syntax to `JavaScript`**, in order to be able to **find errors much more quickly in your Editor** (for example, in VS-Code).
- `TypeScript` code **is convertible** into `JavaScript` code. Thus, TypeScript is able to run anywhere, where JavaScript runs.

### Quelle

- <u>**Webseite (Home)**</u>: https://www.typescriptlang.org/
- <u>**Documentation**</u>: https://www.typescriptlang.org/docs/handbook/intro.html


## MongoDB

### Was ist das?

- `MongoDB` is a **document-oriented**, **no sequel (NoSQL)** database.

### Quelle

- <u>**Tutorial von `WebDevSimplified`**</u>: https://www.youtube.com/watch?v=ofme2o29ngU
- <u>**Documentation**</u>: https://docs.mongodb.com/manual/installation/

## Kubernetes

### Was ist das?

- Kubernetes ist ein Open-Source-System zur Automatisierung der Bereitstellung, Skalierung und Verwaltung von containerisierten Anwendungen. Das Open-Source Project wird von der Cloud Native Computing Foundation (CNCF) gehosted.

### Quellen 

- <u>Documentation</u>: https://kubernetes.io/de/docs/home/

